[build]
builder = "NIXPACKS"
watchPatterns = ["src/**/*"]
buildCommand = "npm run build:frontend"

[deploy]
startCommand = "npm run start:frontend"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"