[build]
builder = "nixpacks"
buildCommand = "npm run build:frontend"

[deploy]
startCommand = "npm run start:frontend"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[deploy.envs]
NODE_ENV = "production"
